apiVersion: apps/v1
kind: Deployment
metadata:
  name: proton
  namespace: proton
  labels:
    app: proton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proton
  template:
    metadata:
      labels:
        app: proton
    spec:
      containers:
        - name: proton
          # Use 'proton:latest' if building locally, 
          # or your registry path e.g. 'ghcr.io/user/proton:v1'
          image: "docker.io/g3n3zyp/proton:latest"
          imagePullPolicy: Always # Important for local k3s images import
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
          - mountPath: /app/storage
            name: proton-files
      volumes:
      - name: proton-files
        persistentVolumeClaim:
          claimName: proton-files
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proton-files
  namespace: proton
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: proton
  namespace: proton
  labels:
    app: proton
    component: service
spec:
  type: LoadBalancer
  selector:
    app: proton
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 3000
---    
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-proton
  namespace: proton
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: proton.48340.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proton
                port:
                  number: 80
  tls:
    - hosts:
        - proton.48340.xyz
      secretName: proton-http-tls
